name: Discord Commits

on: 
  pull_request:
    branches: [ main ]

jobs:
  discord:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.8
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }} # Atenção: nesta action o nome costuma ser 'webhook'
          template: "avatar-with-link"
          include-extras: true