name: Discord Webhook

on: 
  pull_request:
    branches: [ main ]

jobs:
  discord:
    runs-on: ubuntu-latest
    # Adicionamos permissão de leitura para a Action conseguir ver os commits
    permissions:
      contents: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Atualizei para a v4 (mais estável)
        with:
          fetch-depth: 0 # CRUCIAL: Baixa todo o histórico para a Action não ler "undefined"

      - name: Run Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}